### PR TITLE
Develop into Master

### PR DESCRIPTION
**Pull request by ahurli**
Merging Develop into Master, which will be tagged with a new release. See below for the release notes.

**Closed Issues:**
- Allow user to specify more parameters for energy storage (#380)
- Execute.launch_simulation does not check current ExecuteList status (#377)
- Report investment costs disaggregated by zone (#368)
- Improve flexibility of simulation engine input preparation process (#364)
- Specify grid model in building phase of a scenario (#351)
- Load and transform US normalized profiles (#350)
- Switch to newly constructed USA profiles (#349)
- Normalize hydro, solar and wind profiles (#347)
- Identify relevant profiles (#346)
- Delete outdated/bugged scenarios (#345)
- Grid model selection (#344)
- Add one-way DC line (#342)
- Add bus via change table (#341)
- Renewable generators cost curves (#332)
- Transmission "traffic map" web compatibility improvements (#307)
- Remove redundant id2type and type2id dictionaries from Grid (#288)
- Error If ScenarioData folder does not exists on local  (#272)
- Build data access layer for scenario and execute list using sql db (#270)
- Create module enclosing historical data (#268)
- Create module enclosing generators constants (#265)
- Rename module (#263)
- Organize TAMU network constants (#262)
- Base grid should not be used when scaling profile (#260)
- Pmax of closest neighbor in TransformProfile  (#259)
- Improve test cobverage of TransformProfile class (#254)
- Access profiles in the create state (#248)
- If a base profile is interrupted during download, it will be used to prepare an incomplete profile (#246)
- Reorganize package (#244)
- Handle the error if the script failed to change 'ScenarioList.csv' or 'ExecuteList.csv' (#241)
- Change paths to data folders and model (#234)
- Use ralative path to base profiles in tmp folder (#230)
- Allow interaction with locally-cached scenario data files via locally-cached ScenarioList (#228)
- Set REISE.jl as the default engine (#226)
- loadzone2state in powersimdata.utility.constants doesn't contain Western/Texas zones (#225)
- pandas deprecation warning (#224)
- Web compatibility of bokeh maps (#218)
- Added HVDC and AC lines hav wrong index (#215)
- Enable loading of scenarios located in RE-Storage (#214)
- Create a move state in the scenario framework (#213)
- Get rid of symbolic link to profile (#212)
- Implement communication between zeus and RE-Storage (#211)
- Update README (#202)
- Set up automated linting  (#198)
- Streamline the capacity scaling process (#195)
- Get grid in the create and execute states (#190)
- Create TransformGrid and ScaleProfile Class (#189)
- Refactor Scaler Class (#188)
- Running tests now creates a diff due to saved capacity scaling demo (#185)
- Grid fields cannot be modified with conventional syntax (#178)
- New AC branches are not added to the branch data frame (#176)
- Add get_load_shed method to Analyze (#175)
- Modify Collaborative strategy so that states without goals do not participate (#171)
- Profiles are not returned properly for a scenario with fewer solar/wind plants (#169)
- Add filtering of lines available for mesh branch upgrade design (#168)
- Add ability to add new AC branches via a change table (#154)
- Add ability to add new plants to a Grid via a change table (#153)
- Add ability to modify cost curves via change table (#142)
- Add step to select engine when creating a scenario (#139)
- Use call and extract_data modules in REISE (#133)
- Create design folder; move into it capacity planning, design transmission, and scenario info (#138)
- Capacity Planning: add direct output of change table (#127)
- Add ability to prioritize which mesh branches to upgrade when designing Scenarios (#116)
- Ability to add new HVDC lines to Scenario object in Create state (#114)
- Refactor grid scaling: create grid field object (#112)
- Refactor Scaling Procedure (#111)
- Delete properly scenario in Execute List (#107)
- Tests of capacity scaling fail (#96)
- Implement ScenarioInfo Object (#93)
- cost planning (#91)
- Remove Seaborn as a dependency (#87)
- Write Reader for MATLAB File (#86)
- Specify Grid Model in Scenario List (#84)
- Grid Building (#83)
- IVU Speaker Series Presentation: Development of materials and coordination (#81)
- Enable USA (#77)
- File Deletion in Local Directory (#64)
- Get Data Frame of PF on DC Line (#62)
- Modify REISE scenario code to resume scenario run (#205)
- Storage setup without request  (#60)
- Eastern Interconnection (#56)
- Path of lockfile (#54)
- congestion analysis and mapping (#45)
- solar curtailment Utah and Colorado - base case investigation (#44)
- interactive mapping tool - bus connections feature add (#38)
- Enable Texas in Scenario object (#37)
- Enable Texas+Western in Scenario object (#36)
- On a Windows machine, Scenarios can be created but simulations can't be launched (#34)
- Index shoud be key not i (#30)
- Scaled profile are note deleted after being uploaded to server (#27)
- Map aux file to mpc file (#25)
- Explicitly name the fields that go into the MPC struct (#24)
- Make the data manipulation sections of the code more functional (#21)
- Instances of the state object are dynamically changed between inherited types (#20)
- Have a separate file for each class (#19)
- Test Scenario Object  (#17)
- WECC Congestion Analysis General Function Development (#11)
- Tutorial for Scenario Object (#7)
- Transfer California input and output files to new data structure (#6)
- Paramiko 2.4.2 does not support some types of ssh-keys. (#204)
- Modify Synthetic Grid (#5)
- Change Table (#4)
- Workflow Version 2 (#3)
- Data Storage on Server (#2)
- Create Scenario class. (#1)

Merged pull requests (features):
- Enable grid model selection (#414) (@rouille)
- feat: add optional solver parameter to launch_simulation (#404) (@jon-hagg)
- feat: add temporal curtailment calculation (#401) (@danielolsen)
- feat: add with syntax to PrintManager (#390) (@danielolsen)
- feat: add method to check progress of ongoing simulation (#387) (@jon-hagg)
- feat: let user specify more parameters for storage (#383) (@danielolsen)
- feat: add storage_pg entry to MockAnalyze (#381) (@BainanXia)
- DataAccess implementation for shared volume architecture (#376) (@jon-hagg)
- Add method to retrieve scenario table (#373) (@rouille)
- Client code to launch simulation in container (#369) (@jon-hagg)
- update color and label dictionaries to include default values for curtailments (#366) (@BainanXia)
- Update parameters of connection to server (#356) (@dmuldrew)
- Add ability to add DC lines with different Pmin and Pmax (#355) (@danielolsen)
- Ability to add buses to the grid via the Change Table (#352) (@danielolsen)
- Improve clearing of Change Table entries (#348) (@danielolsen)
- Create mapping between load zone IDs and time zones (#339) (@lanesmith218)
- lazy ssh connection (#334) (@jon-hagg)
- Add ability to scale generator Pmin via ChangeTable (#333) (@danielolsen)
- Create an abstraction for the SSH connection to the data store (#330) (@danielolsen)
- Update call to engine (#324) (@ahurli)
- Improve Grid and Scenario init flexibility (#323) (@danielolsen)
- Add ability to scale gencost from change table (#322) (@danielolsen)
- Allow user to specify that profiles are the same as a previous scenario (#313) (@danielolsen)
- Add get_bus_demand method (#311) (@danielolsen)
- Enable optional requirements (#310) (@danielolsen)
- Dockerfile for powersimdata (#308) (@jon-hagg)
- Add simple cache for grid object (#305) (@jon-hagg)
- Supply and Cost Curve Visualizations (#299) (@lanesmith218)
- Investment costs (#297) (@nina-vincent)
- interconnect to time zone (#295) (@rouille)
- When creating a MockAnalyze, ensure dataframe indices are time series (#294) (@danielolsen)
- Within capacity scaling, detect zones collisions and add ability to specify target area type (#284) (@danielolsen)
- Add dictionaries to zones module (#281) (@rouille)
- create schema in container automatically (#275) (@jon-hagg)
- Add constants to plant module (#273) (@rouille)
- Database layer for scenario and execute list (#266) (@jon-hagg)
- Locally cache execute list (#257) (@jon-hagg)
- Enable local caching of scenario list (#252) (@jon-hagg)
- refactor: conduct capacity scaling via dataframes (#250) (@danielolsen)
- Access profiles in the create state (#249) (@rouille)
- feat: centralize execute list access (#247) (@jon-hagg)
- fix loadzone2state, add loadzone2interconnect (#242) (@danielolsen)
- chore: type-checking and documentation for threads selection (#239) (@danielolsen)
- feat: remove potential whitespace in username (#238) (@jon-hagg)
- feat: specify number of threads to use to run simulation (#237) (@danielolsen)
- feat: add get_server_user function (#236) (@danielolsen)
- feat: set REISE.jl as default engine (#226) (#229) (@rouille)
- Read from backup (#222) (@rouille)
- Write Move class (#221) (@rouille)
- Extend mappings to include usa and texas western (#208) (@jon-hagg)
- feat: redirect output stream to os.devnull via parameters of Popen (#203) (@BainanXia)
- Filter mesh branch upgrades (#196) (@danielolsen)
- Add generators via change table (#194) (@rouille)
- feat: enable get_load_shed from Analyze (#193) (@danielolsen)
- Refactor Scaler Class (#186) (@rouille)
- feat: create change table to mimic existing grid when scaling new grid (#174) (@danielolsen)
- Add acline via ct (#173) (@rouille)
- Update collaborative strategy: ignore states without goals (#172) (@danielolsen)
- Add dcline through change table (#166) (@rouille)
- Set collab solar fraction (#164) (@danielolsen)
- feat: scale hydro stub branches (#163) (@danielolsen)
- feat: add capability to scale offshore wind (#159) (@danielolsen)
- feat: add requirements_freeze.txt file to help lock down a working environment (#155) (@dmuldrew)
- feat: test for Grid equality (#152) (@danielolsen)
- feat: add REISEjlMATReader to interpret input.mat from REISE.jl (#150) (@danielolsen)
- Grid Scaling: hierarchical grid field class (#149) (@dmuldrew)
- Add step to set simulation engine when creating a scenario (#141) (@rouille)
- Grid field (#137) (@dmuldrew)
- Collaborative addl curtailment rebased (#136) (@dmuldrew)
- Get averaged congestion via the Scenario object (#123) (@rouille)
- Getter grid (#121) (@dmuldrew)
- feat: mesh branch upgrade priorities (#120) (@danielolsen)
- feat: adds Resource Manager to integrate existing notebook code (#119) (@dmuldrew)
- Set additional curtailment function within capacity framework (#117) (@dmuldrew)
- feat: add info attribute to ScenarioInfo class (#113) (@BainanXia)
- Capacity planning resource manager (#109) (@dmuldrew)
- Write MATReader object (#98) (@rouille)
- feat: add_zone2_to_mock_grid (#95) (@BainanXia)
- Create ScenarioInfo class (#94) (@BainanXia)
- feat: Scale mesh branches (#89) (@danielolsen)
- feat: capacity scaling framework (#88) (@dmuldrew)
- Create grid object from different sources (#85) (@rouille)
- feat: add module to 'design' scenarios, starting with renewable stub scaling (#80) (@danielolsen)
- Enable USA scenario (#79) (@rouille)
- feat: support for 'biomass' and 'other' generators (#71) (@danielolsen)
- Get power flow on dcline (#63) (@rouille)
- Add storage (#59) (@rouille)
- feat: Enable Eastern interconnection (#57) (@rouille)
- feat: Add dcline id to case file (#23) (#53) (@rouille)
- Enable Texas scenario (#41) (@rouille)
- Update usa_tamu files (#40) (@BainanXia)
- feat: add fuel cost and heat-rate curve to grid object (#29) (@ghost)
- feat: ability to add storage in change table (#26) (@ghost)
- Create Scenario class (#12) (@rouille)

Merged pull requests (fixes, etc.):
- fix: correct bug with carried-over gencosts for new plants (#407) (@danielolsen)
- refactor: move generation of matfile to separate function (#406) (@danielolsen)
- ci: use pre defined action to trigger workflow (#402) (@jon-hagg)
- Upgrade numpy/scipy (#400) (@jon-hagg)
- Update link in PR template (#399) (@rouille)
- chore: update package version number (#397) (@kasparm)
- chore: update email in datapackage.json (#396) (@danielolsen)
- docs: add link to installation and contribution guide (#395) (@kasparm)
- data: set Pmin for solar and wind gens to 0 (#394) (@danielolsen)
- chore(deps): bump cryptography from 3.3.1 to 3.3.2 (#393) (@dependabot[bot])
- fix: calculate investment cost for nuclear generators (#391) (@danielolsen)
- ci: use black profile for isort (#389) (@jon-hagg)
- refactor: remove redundant function for getting bus demand (#388) (@danielolsen)
- doc: update investment cost README for current calculations (#385) (@danielolsen)
- fix: correct bug with repeated substation in TransformGrid._add_bus (#384) (@danielolsen)
- Set keyword value (#379) (@rouille)
- Update scenario status (#378) (@rouille)
- fix: change caught Exception for get_load_shed (#375) (@danielolsen)
- test: remove index column from test assertion (#374) (@jon-hagg)
- doc: fix docstring reference to new DataAccess location (#372) (@danielolsen)
- fix: get newer pipenv and fix installation in docker (#371) (@jon-hagg)
- fix: add requests to setup.py (#370) (@jon-hagg)
- Move data access classes to eponymous package (#367) (@jon-hagg)
- Remove reference to deleted constant and slight pandas refactor (#365) (@jon-hagg)
- Fix MATReader when loading one Storage and/or zero DC-lines (#363) (@danielolsen)
- Grid equality bugfix (storage) and print improvement (#362) (@danielolsen)
- fix: correct type of new bus index in Grid.bus2sub (#361) (@danielolsen)
- refactor: use Docker CMD for easier overrides (#360) (@dmuldrew)
- Fix delete functionality (#359) (@jon-hagg)
- Change flock command argument (#358) (@dmuldrew)
- Use up to date Western scenario in README (#357) (@rouille)
- Add license (#354) (@rouille)
- Create data intake template (#353) (@rouille)
- Update links in README (#343) (@rouille)
- Use relative paths and mirror server file structure locally (#340) (@jon-hagg)
- fix: scenario state cannot load data (#338) (@merrielle)
- Make test more robust (#335) (@jon-hagg)
- Add terms and conditions to ATTRIBUTION file (#329) (@rouille)
- Improve README (#328) (@rouille)
- Clean notebooks (#327) (@rouille)
- ci: add flake8 and fix warnings (#326) (@jon-hagg)
- fix: typo in delete_entry (#325) (@danielolsen)
- doc: update zenodo reference to permalink (#321) (@danielolsen)
- Add PR template (#320) (@jon-hagg)
- Attribution file (#319) (@rouille)
- Fix docstring (#318) (@rouille)
- Fix typos in #313 (#317) (@danielolsen)
- Remove dependency on geopy (#316) (@danielolsen)
- fix: typo in tox.ini (#315) (@jon-hagg)
- Remove unused imports/depenencies (#314) (@danielolsen)
- fix: improve error message for truncated file download (#309) (@danielolsen)
- chore: refactor ci and test against multiple python versions (#303) (@jon-hagg)
- Ben/zones (#302) (@rouille)
- Trigger docs build (#296) (@jon-hagg)
- data: add nox and so2 emissions rates (#293) (@danielolsen)
- refactor: remove unused id2type and type2id (#292) (@danielolsen)
- refactor: add mwmiles calculations to design.transmission module (#291) (@danielolsen)
- Update pandas (#290) (@jon-hagg)
- Combine ci workflows with tox (#289) (@jon-hagg)
- Update README (#287) (@rouille)
- Fix warnings from sphinx build (#286) (@jon-hagg)
- intvenlab -> Breakthrough-Energy (#285) (@jon-hagg)
- Define db and ssh test markers and run db tests in ci pipeline (#279) (@jon-hagg)
- fix: update paramiko and create local directory if needed (#278) (@jon-hagg)
- Run latest formatting to fix CI (#277) (@jon-hagg)
- Remove previous capacity scaling framework (#276) (@danielolsen)
- chore: add psycopg2 to setup.py (#274) (@jon-hagg)
- Create module enclosing generators constants (#267) (@rouille)
- Rename module (#264) (@rouille)
- Use transformed grid in scaling procedure (#261) (@rouille)
- Update __init__ file (#258) (@rouille)
- Improve test coverage of TransformProfile class (#253) (@rouille)
- Fix bugs in TransformProfile class (#251) (@danielolsen)
- Move data and modules around (#245) (@rouille)
- Consolidate scenario list access to go through one class (#240) (@jon-hagg)
- Change paths to data folders and model (#235) (@rouille)
- Redo PR after fixing develop (#233) (@jon-hagg)
- pandas deprecation warning (#232) (@rouille)
- switch to relative path (#231) (@rouille)
- Mock scenario info and some code cleanup (#227) (@jon-hagg)
- Package update/consolidation (#223) (@jon-hagg)
- Add pipfile and update packages (#220) (@jon-hagg)
- Use base profile directly  (#217) (@rouille)
- Fix indexing of added HVDC and AC lines (#216) (@rouille)
- Specify installation dependencies for consumers (#210) (@jon-hagg)
- Rewrite sections 1 and 2 of README (#209) (@rouille)
- Run black on the code and add ci check (#207) (@jon-hagg)
- data: align GenFuelCost to gencost (c1, c2) (#206) (@danielolsen)
- Run pytest in github action (#201) (@jon-hagg)
- fix: allow small negative value for prev_curtailment (#197) (@danielolsen)
- Set capacities of unused HVDC lines to zero (#192) (@rouille)
- refactor: clean up after capacity scaling tests (#191) (@danielolsen)
- data: Generation update Western & Texas since 2016 (#187) (@danielolsen)
- refactor: historical clean energy is additional, not reference (#184) (@danielolsen)
- test: create tests for grid equality (#183) (@danielolsen)
- refactor: remove grid fields dependency from develop (#182) (@dmuldrew)
- fix: allow small tolerance on capacity factors (#181) (@danielolsen)
- data: update hvdc and cost curve according to real values (#180) (@BainanXia)
- Fix getter grid setattr (#179) (@danielolsen)
- Append new branches to branch data frame of Grid object (#177) (@rouille)
- fix: populate optional area_type to all related functions (#170) (@BainanXia)
- data: revert Pmax changes to hydro, update branch instead (#167) (@danielolsen)
- data: update hydro Pmax to reflect latest profile max (#162) (@danielolsen)
- chore: enable selection of REISE.jl engine (#161) (@danielolsen)
- data: add offshore wind to grid (#160) (@danielolsen)
- fix: change unexpected modifications in Western and Texas back (#158) (@BainanXia)
- Move modules (#156) (@rouille)
- Fix: avoid entries in Grid fields entries being shared between instances (#151) (@danielolsen)
- refactor: set up flexibility for multiple versions of MATReader (#148) (@danielolsen)
- Fix engine in test (#146) (@rouille)
- refactor: remove seaborn as a dependency (#145) (@danielolsen)
- data: update ramp_30 to match what is sent to the solver (#144) (@danielolsen)
- chore: remove unused CollaborativeStrategyManager method (#140) (@danielolsen)
- Fix mesh bug existing ct (#135) (@danielolsen)
- Use call and extract_data modules from REISE (#134) (@rouille)
- refactor: reduce memory requirements for mesh branch scaling (#132) (@danielolsen)
- Deepcopy fix (#131) (@dmuldrew)
- fix: incorporate collaborative scaling overgeneration (#129) (@danielolsen)
- fix: avoid error when scaling from scenario with slightly negative generation (#128) (@danielolsen)
- Move modules (#126) (@rouille)
- fix: enable MATReader to import single DC line from case.mat (#125) (@danielolsen)
- chore: create a design folder for capacity planning, design transmission, scenario info (#124) (@dmuldrew)
- Update import statement (#122) (@rouille)
- data: Eastern generation update since 2016 (#118) (@danielolsen)
- data: Eastern generation update 2017-2020 (#115) (@danielolsen)
- data: upgrading transmission in North GA to relieve solar curtailment (#110) (@danielolsen)
- fix: Delete correct scenario in ExecuteList file (#108) (@rouille)
- fix: update area filter in area_to_loadzone function (#106) (@BainanXia)
- refactor: more intermediate output columns and input validation (#105) (@dmuldrew)
- data: Eastern v41 data fixes (#104) (@danielolsen)
- docs: add a cheatsheet demo notebook to see Scenario, Analyze, and Grid attributes and dataframe schemas (#103) (@merrielle)
- chore: PEP 8 and file path tweaks (#102) (@dmuldrew)
- doc: documentation of features in design_transmission (#101) (@danielolsen)
- doc: adding datapackage.json for tabular data package (#99) (@danielolsen)
- data: updates to Eastern data due to feasibility/sensibility testing (#97) (@danielolsen)
- chore: add pycharm and os files to gitignore (#78) (@merrielle)
- data: adding solar and wind generators to eastern (#76) (@danielolsen)
- data: improved eastern transmission feasibility for new hydro/solar/wind profiles (#75) (@danielolsen)
- data: upgrades to eastern transmission for base case feasibility (#74) (@danielolsen)
- data: feasibility fix for Western peak (#73) (@danielolsen)
- data: adding generators of 'other' type to eastern (#72) (@danielolsen)
- docs: update pandas version in requirements (#70) (@merrielle)
- data: Intra-interconnection HVDC lines (#69) (@danielolsen)
- chore: add gitignore file (#68) (@merrielle)
- fix: Correct bug related to scenario deletion (#64) (#65) (@rouille)
- fix: avoid storage mat with empty change table (#61) (@ghost)
- data: fix eastern dfo prices (and floating point cruft) (#58) (@ghost)
- fix: Solve path of lockfile (#54) (#55) (@rouille)
- Fix cost curve texas (#52) (@BainanXia)
- fix: Scale Pmin of dc line. Same value than Pmax is used. (#51) (@rouille)
- fix: upgrading texas transmission network to avoid unrealistic load c… (#50) (@ghost)
- data: western transmission upgrade to avoid unreasonable curtailment (#49) (@ghost)
- data: change dcline pmin to negative of pmax (#48) (@ghost)
- fix: scale pmax for renewable gens (#47) (@ghost)
- fix: Relocate lockfile to enable rw by group (#46) (@rouille)
- Fix cost curve wecc for coal and ng (#43) (@BainanXia)
- fix: TAMU transformers (#39) (@BainanXia)
- fix: Sole issue #34 for Windows users (#35) (@rouille)
- fix: relocating geothermal to avoid unrealistic congestion (#33) (@ghost)
- fix: use UNIX path (#32) (@rouille)
- fix: #30 Set index i to key (#31) (@kasparm)
- fix: Delete profile in local folder after upload to server (#28) (@rouille)
- fix: when scaling gen Pmax, also scale Pmin and cost curve (#16) (@ghost)

### CODE REVIEW

**Comment by danielolsen** [comment]
If the `model` branch is expected to get merged in the next day or two, should we try to get that into this release as well? That's a pretty major feature.

**Comment by rouille** [comment]
> If the `model` branch is expected to get merged in the next day or two, should we try to get that into this release as well? That's a pretty major feature.

We probably do.

**Comment by rouille** [comment]
Looks very nice. Thanks! Would it be possible to add the last issues/PRs related to the grid model selection feature?

**Comment by ahurli** [comment]
Done! Added in the new PRs/Issues. Note that both are ordered by number and not date closed, so the new PRs and Issues are embedded accordingly.

**Comment by ahurli** [comment]
Done! Added in the new PRs/Issues. Note that both are ordered by number and not date closed, so the new PRs and Issues are embedded accordingly.

**Comment by ahurli** [comment]
Per conversation with Ben, I updated the list so that PRs that were not merged are excluded. I also filtered the PR list such that if any commit in the PR was listed as a "feat:", the PR was categorized as a feature PR. I think this should have caught most of the PRs with names that don't have that descriptor, but also has some interesting consequence that PRs like #94 or #239, which are named 'fix:' and 'chore:', have feature commits and are thus categorized as such. In these cases, is there a strong feeling of where to put them?

**Comment by rouille** [comment]
I have changed the title of some PRs for clarity. You will have to rerun your scripts. i believe we will have to fix the following two entries manually:
* Collaborative addl curtailment (#130) (@dmuldrew) 
* Collaborative addl curtailment rebased (#136) (@dmuldrew)
I would say that #130 has been merged without rebasing. The HEAD of `develop` has then been reset and #136 has been merged. So we can drop #130 in the notes and rename #136: `Collaborative addl curtailment (#136) (@dmuldrew)`

**Review by rouille — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
