### PR TITLE
chore: update packages, apply latest black formatting

### PR DESCRIPTION
**Pull request by jenhagg**
[Pull Request doc](https://breakthrough-energy.github.io/docs/user/git_guide.html#d-pull-request)

### Purpose
Fix the formatting check by applying the latest black. Regenerate Pipfile.lock which includes an update to `exceptiongroup` rather than removal, which is what was done by dependabot for some reason.

### What the code is doing
See above

### Testing
Ran tox locally

### Time estimate
3 min

### CODE REVIEW

**Review by BainanXia — APPROVED** [review]
🙏

Wait: it seems some tests are failing.

**Comment by jenhagg** [comment]
> 🙏
> 
> Wait: it seems some tests are failing.

Yeah it seems `xarray` is updated to a version that requires python 3.9. We might have to pin that version by adding it to the Pipfile, since I don't think we can specify a minimum python version (only exact). 

edit: alternatively, we could drop 3.8 from the checks? I think someone could still install the packages in a 3.8 environment since they aren't specified exactly in setup.cfg or requirements.txt, only in Pipfile.lock. That might, however, require a user running tox locally (thus installing from Pipfile.lock) to be using `>=3.9`.

**Comment by rouille** [comment]
> > 🙏
> 
> > 
> 
> > Wait: it seems some tests are failing.
> 
> 
> 
> Yeah it seems `xarray` is updated to a version that requires python 3.9. We might have to pin that version by adding it to the Pipfile, since I don't think we can specify a minimum python version (only exact). 
> 
> 
> 
> edit: alternatively, we could drop 3.8 from the checks? I think someone could still install the packages in a 3.8 environment since they aren't specified exactly in setup.cfg or requirements.txt, only in Pipfile.lock. That might, however, require a user running tox locally (thus installing from Pipfile.lock) to be using `>=3.9`. 

Yes we can drop 3.8 and add 3.11. A final update before saying 👋

**Review by rouille — APPROVED** [review]
Thanks

**Pull request merged**
