### PR TITLE
fix: correct bug with carried-over gencosts for new plants

### PR DESCRIPTION
**Pull request by danielolsen**
### Purpose
Fix the bug, where new renewable generators added after a thermal generator inherit the thermal generator's cost curve coefficients.

### What the code is doing
The first commit reproduces the code in a test, the second commit fixes it by ensuring that no values are carried over.

### Time estimate
1 minute.

### CODE REVIEW

**Review by BainanXia — APPROVED** [review]
Good catch!

**Comment by rouille** [comment]
Should we move in the `for` loop the other too (`new_branch`, `new_plant`, etc.)?

**Comment by danielolsen** [comment]
> Should we move in the `for` loop the other too (`new_branch`, `new_plant`, etc.)? I mean we need to set the value of the columns to 0 for all of them in principle.

The problem that is specific to gencost is the `if` block which updates those entries only sometimes. It should not be a problem for the other loops which do not have this feature, but it is probably good practice to move them all, to avoid this issue potentially arising later.

**Comment by danielolsen** [comment]
The analogous line has been moved inside the loops in the other add methods.

**Review by rouille — APPROVED** [review]
Makes sense

**Pull request merged**
