### PR TITLE
Fix bus assignment/naming and add geographical coordinates to branch and plant 

### PR DESCRIPTION
**Pull request by FabianHofmann**
Always add geo coordinates to branch and plant when importing from pypsa. 

### Purpose
Dicussed in the meeting

### Testing
Automatic

### Time estimate
5 min

### CODE REVIEW

**Review by jenhagg — APPROVED** [review]

**Review by BainanXia — APPROVED** [review]

**Comment by rouille** [comment]
@FabianHofmann, can you rebase onto `ben/import` and force push, I have just merged #691 into `ben/import` so the HEAD has changed. Thanks!

**Comment by FabianHofmann** [comment]
great, here we go :)

**Comment by rouille** [comment]
@FabianHofmann, the `inflow` plants don't coordinates:
```
(TUB) [~/Collaboration/TUB] (pypsa-lat-lon-assignment) brdo$ python
Python 3.10.3 (main, Mar 24 2022, 16:46:35) [Clang 12.0.0 (clang-1200.0.26.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from powersimdata.network.europe_tub.model import TUB
>>> from powersimdata.input.converter.pypsa_to_grid import FromPyPSA
>>> tub = TUB("Europe", reduction=128)
Title: PyPSA-Eur: An Open Optimisation Model of the European Transmission System (Dataset)
Publication date: 2022-09-20
Version: v0.6.1
DOI: 10.5281/zenodo.7251657
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.66G/1.66G [05:47<00:00, 5.13MB/s]
>>> tub.build()
INFO:pypsa.io:Imported network elec_s_128_ec.nc has buses, carriers, generators, lines, links, loads, storage_units, stores
>>> grid = FromPyPSA(tub.network)
>>> grid.plant[["lat", "lon"]]
                          lat        lon
plant_id                                
AL1 0 offwind-ac    41.587568  19.897914
AL1 0 oil           41.587568  19.897914
AL1 0 onwind        41.587568  19.897914
AL1 0 ror           41.587568  19.897914
AL1 0 solar         41.587568  19.897914
...                       ...        ...
SE2 2 hydro inflow        NaN        NaN
SE2 3 hydro inflow        NaN        NaN
SE2 4 hydro inflow        NaN        NaN
SI1 0 hydro inflow        NaN        NaN
SK1 0 hydro inflow        NaN        NaN

```

**Comment by rouille** [comment]
Thanks for the fix @chrstphtrs. We could also, I guess, add the coordinates to the `plant` data frame right after `plant = pd.concat([plant, gen_inflow])`.

**Comment by rouille** [comment]
I am not sure this is the right place but there is an issue with the buses in the converter:
```
>>> from powersimdata.network.europe_tub.model import TUB
>>> from powersimdata.input.converter.pypsa_to_grid import FromPyPSA
>>> tub = TUB("Europe", reduction=128)
Title: PyPSA-Eur: An Open Optimisation Model of the European Transmission System (Dataset)
Publication date: 2022-09-20
Version: v0.6.1
DOI: 10.5281/zenodo.7251657
networks.zip has been downloaded previously
>>> tub.build()
WARNING:pypsa.io:
Importing PyPSA from older version of PyPSA than current version.
Please read the release notes at https://pypsa.readthedocs.io/en/latest/release_notes.html
carefully to prepare your network for import.
Currently used PyPSA version [0, 20, 1], imported network file PyPSA version [0, 20, 0].

INFO:pypsa.io:Imported network elec_s_128_ec.nc has buses, carriers, generators, lines, links, loads, storage_units, stores
>>> grid = FromPyPSA(tub.network)
>>> grid.plant["bus_id"].unique()
array(['AL1 0', 'AT1 0', 'AT1 1', 'BA1 0', 'BE1 0', 'BE1 1', 'BE1 2',
       'BG1 0', 'CH1 0', 'CZ1 0', 'CZ1 1', 'DE1 0', 'DE1 1', 'DE1 10',
       'DE1 11', 'DE1 12', 'DE1 13', 'DE1 14', 'DE1 15', 'DE1 16',
       'DE1 17', 'DE1 18', 'DE1 19', 'DE1 2', 'DE1 3', 'DE1 4', 'DE1 5',
       'DE1 6', 'DE1 7', 'DE1 8', 'DE1 9', 'DK1 0', 'DK2 0', 'EE6 0',
       'ES1 0', 'ES1 1', 'ES1 2', 'ES1 3', 'ES1 4', 'ES1 5', 'ES1 6',
       'ES1 7', 'ES1 8', 'ES4 0', 'FI2 0', 'FI2 1', 'FI2 2', 'FR1 0',
       'FR1 1', 'FR1 10', 'FR1 11', 'FR1 12', 'FR1 13', 'FR1 14',
       'FR1 15', 'FR1 16', 'FR1 17', 'FR1 18', 'FR1 2', 'FR1 3', 'FR1 4',
       'FR1 5', 'FR1 6', 'FR1 7', 'FR1 8', 'FR1 9', 'GB0 0', 'GB0 1',
       'GB0 10', 'GB0 11', 'GB0 12', 'GB0 2', 'GB0 3', 'GB0 4', 'GB0 5',
       'GB0 6', 'GB0 7', 'GB0 8', 'GB0 9', 'GB5 0', 'GR1 0', 'HR1 0',
       'HU1 0', 'IE5 0', 'IT1 0', 'IT1 1', 'IT1 10', 'IT1 11', 'IT1 2',
       'IT1 3', 'IT1 4', 'IT1 5', 'IT1 6', 'IT1 7', 'IT1 8', 'IT1 9',
       'IT3 0', 'LT6 0', 'LU1 0', 'LV6 0', 'ME1 0', 'MK1 0', 'NL1 0',
       'NL1 1', 'NL1 2', 'NL1 3', 'NO2 0', 'NO2 1', 'NO2 2', 'NO2 3',
       'NO2 4', 'PL1 0', 'PL1 1', 'PL1 2', 'PL1 3', 'PL1 4', 'PT1 0',
       'PT1 1', 'RO1 0', 'RO1 1', 'RS1 0', 'SE2 0', 'SE2 1', 'SE2 2',
       'SE2 3', 'SE2 4', 'SI1 0', 'SK1 0'], dtype=object)
>>> grid.bus.index
Index(['AL1 0', 'AT1 0', 'AT1 1', 'BA1 0', 'BE1 0', 'BE1 1', 'BE1 2', 'BG1 0',
       'CH1 0', 'CZ1 0',
       ...
       'RO1 0 hydro', 'RO1 1 hydro', 'RS1 0 hydro', 'SE2 0 hydro',
       'SE2 1 hydro', 'SE2 2 hydro', 'SE2 3 hydro', 'SE2 4 hydro',
       'SI1 0 hydro', 'SK1 0 hydro'],
      dtype='object', name='bus_id', length=457)
>>> grid.bus2sub.index
Index(['AL1 0', 'AT1 0', 'AT1 1', 'BA1 0', 'BE1 0', 'BE1 1', 'BE1 2', 'BG1 0',
       'CH1 0', 'CZ1 0',
       ...
       'RO1 0 battery', 'RO1 1 battery', 'RS1 0 battery', 'SE2 0 battery',
       'SE2 1 battery', 'SE2 2 battery', 'SE2 3 battery', 'SE2 4 battery',
       'SI1 0 battery', 'SK1 0 battery'],
      dtype='object', name='bus_id', length=384)
```
* `bus_id` in the `plant` data frame have different names than the indices (`bus_id`) of the `bus` data frame. 
* the number of buses in the `bus` data frame is different than in the `bus2sub` data frame. For example, `SK1 0 hydro` is in `bus` but not in `bus2sub` 
```
>>> grid.bus2sub.loc['SK1 0 hydro']
Traceback (most recent call last):
  File "/Users/brdo/.local/share/virtualenvs/PowerSimData-MpUK62nT/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3803, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'SK1 0 hydro'
```

**Comment by FabianHofmann** [comment]
@rouille thanks for checking carefully, we'll fix it tomorrow morning

**Comment by FabianHofmann** [comment]
@rouille I made a correction, could you test it out?

**Review by rouille — APPROVED** [review]

**Pull request merged**
