### PR TITLE
feat: add with syntax to PrintManager

### PR DESCRIPTION
**Pull request by danielolsen**
### Purpose
Allow the use of the `with` statement with the `PrintManager`.

### What the code is doing
`__enter__` and `__exit__` functions are added, as documented in https://docs.python.org/3/reference/compound_stmts.html#the-with-statement.

### Usage Example/Visuals
Previously, if we wanted to block print for a block of code, we needed to do something like:
```python
>>> pm = PrintManager()
>>> pm.block_print()
>>> demand = scenario.state.get_demand()
>>> pm.enable_print()
```

Now, the same commands can be accomplished via a shorter syntax:
```python
>>> with PrintManager():
...     demand = scenario.state.get_demand()
```

### Time estimate
5 minutes.

### CODE REVIEW

**Review by jon-hagg — APPROVED** [review]
Nice.

**Comment by danielolsen** [comment]
I think this will be useful as we refactor PostREISE; we don't necessarily need to be printing to the user all the details of what's going on under the hood.

**Review by rouille — APPROVED** [review]
Cool

**Review by BainanXia — APPROVED** [review]
Nice.

**Pull request merged**
