### PR TITLE
Add badges to README

### PR DESCRIPTION
**Pull request by rouille**
[Pull Request doc](https://breakthrough-energy.github.io/docs/user/git_guide.html#d-pull-request)

### Purpose
Add badges for the sake of adding badges.

### What the code is doing
N/A

### Testing
N/A

### Where to look
* Made with Python
* Code of conduct
* Contributors
* Commit activity
* Last commit
* Pull Requests open

### Usage Example/Visuals
The badges are displayed [here](https://github.com/Breakthrough-Energy/PowerSimData/blob/ben/badge/README.md)

### Time estimate
N/A

### CODE REVIEW

**Review by kasparm — APPROVED** [review]
Thank you.

This is like nicely wrapping a present.

**Review by jon-hagg — APPROVED** [review]
Good use of the `style:` prefix

**Review by BainanXia — APPROVED** [review]
As @kasparm said, Indeed.

**Comment by rouille** [comment]
Should I add this [one](https://img.shields.io/badge/Made%20with-Python-1f425f.svg)?

**Pull request merged**
